# Generated by Django 5.0.2 on 2024-02-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="trip_type",
            field=models.BooleanField(default=False),
        ),
    ]
