# Generated by Django 5.0.2 on 2024-02-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_trip_trip_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trip",
            old_name="trip_type",
            new_name="future_trip",
        ),
        migrations.AddField(
            model_name="trip",
            name="past_trip",
            field=models.BooleanField(default=False),
        ),
    ]
